### ISSUE TITLE
Unable to get working on Spark Core

### ISSUE THREAD

**Issue by cconway** [novemberfiveco/spark-hih61xx-library#1]
I've been using the HIH6130 successfully with an Arduino Duo and RFduino.  I am trying to use it with with Spark Core but I can't get past Wire.endTransmission returning status code 4. I have done tests using the same HIH device and wiring, using both my library and yours. I just cannot get it to work with Spark Core. Are there any suggestions you can offer that might help me figure this out?

**Comment by GeertWille** [comment]
How does your connection schema look like? Can you attach the main code you working with?

**Comment by cconway** [comment]
I left more of a discussion on the Spark Core boards but in the end after days of trying I went to get my little breadboard out and tried again and it just worked. No reflash, same wiring, etc. it's a real head scratcher.
